# Generated by Django 6.0.4 on 2026-04-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatFoxIOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threatfox_id', models.CharField(max_length=50, unique=True)),
                ('ioc', models.CharField(max_length=255)),
                ('threat_type', models.CharField(blank=True, max_length=100)),
                ('ioc_type', models.CharField(max_length=50)),
                ('malware', models.CharField(blank=True, max_length=100)),
                ('confidence_level', models.IntegerField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('reporter', models.CharField(blank=True, max_length=100)),
                ('tags', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
