# Generated by Django 6.0.4 on 2026-04-11 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0006_providerrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failure', 'Failure')], max_length=20)),
                ('trigger', models.CharField(default='manual', max_length=50)),
                ('requested_provider', models.CharField(blank=True, max_length=100)),
                ('requested_since', models.CharField(blank=True, max_length=100)),
                ('timeout_seconds', models.IntegerField(default=30)),
                ('dry_run', models.BooleanField(default=False)),
                ('feed_refreshed', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('providers_total', models.IntegerField(default=0)),
                ('providers_succeeded', models.IntegerField(default=0)),
                ('providers_failed', models.IntegerField(default=0)),
                ('providers_skipped', models.IntegerField(default=0)),
                ('records_created', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
                ('records_skipped', models.IntegerField(default=0)),
                ('error_summary', models.CharField(blank=True, max_length=500)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProviderRunDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=100)),
                ('run_type', models.CharField(choices=[('ingest', 'Ingest'), ('enrichment', 'Enrichment')], max_length=20)),
                ('enabled_state', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('partial', 'Partial'), ('skipped', 'Skipped')], max_length=20)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('records_fetched', models.IntegerField(default=0)),
                ('records_created', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
                ('records_skipped', models.IntegerField(default=0)),
                ('error_summary', models.CharField(blank=True, max_length=500)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['started_at', 'id'],
            },
        ),
        migrations.RenameIndex(
            model_name='providerrun',
            new_name='intel_provi_provide_62f734_idx',
            old_name='intel_provi_provide_d17a11_idx',
        ),
        migrations.RenameIndex(
            model_name='providerrun',
            new_name='intel_provi_run_typ_88c6b1_idx',
            old_name='intel_provi_run_typ_5467ea_idx',
        ),
        migrations.AddIndex(
            model_name='ingestionrun',
            index=models.Index(fields=['status', '-started_at'], name='intel_inges_status_bb2fd8_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionrun',
            index=models.Index(fields=['trigger', '-started_at'], name='intel_inges_trigger_e42b23_idx'),
        ),
        migrations.AddField(
            model_name='providerrundetail',
            name='ingestion_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_details', to='intel.ingestionrun'),
        ),
        migrations.AddIndex(
            model_name='providerrundetail',
            index=models.Index(fields=['ingestion_run', 'provider_name'], name='intel_provi_ingesti_55cfcd_idx'),
        ),
        migrations.AddIndex(
            model_name='providerrundetail',
            index=models.Index(fields=['provider_name', '-started_at'], name='intel_provi_provide_bc16f9_idx'),
        ),
        migrations.AddIndex(
            model_name='providerrundetail',
            index=models.Index(fields=['run_type', 'status'], name='intel_provi_run_typ_62064a_idx'),
        ),
    ]
