# Generated by Django 5.2.13 on 2026-04-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0010_domainenrichment'),
    ]

    operations = [
        migrations.AddField(
            model_name='intelioc',
            name='calculated_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intelioc',
            name='score_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='intelioc',
            name='score_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='intelioc',
            index=models.Index(fields=['calculated_score'], name='intel_intel_calcula_443dd9_idx'),
        ),
    ]
