# Generated by Django 6.0.4 on 2026-04-13 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0011_intelioc_calculated_score_intelioc_score_breakdown_and_more'),
        ('intel', '0011_intelioc_scoring_fields'),
    ]

    operations = [
    ]
