# Generated by Django 6.0.4 on 2026-04-18 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0013_ticket_ticketnote'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ticket',
            new_name='intel_ticke_status_3cb08e_idx',
            old_name='intel_ticke_status_1df5a4_idx',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='intel_ticke_priorit_8c9f4c_idx',
            old_name='intel_ticke_priorit_52bd79_idx',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='intel_ticke_assigne_63c226_idx',
            old_name='intel_ticke_assigne_a60c60_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketnote',
            new_name='intel_ticke_ticket__f056ec_idx',
            old_name='intel_ticke_ticket__340280_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketnote',
            new_name='intel_ticke_author__26727f_idx',
            old_name='intel_ticke_author__2ed470_idx',
        ),
    ]
