# Generated by Django 6.0.4 on 2026-04-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0014_rename_intel_ticke_status_1df5a4_idx_intel_ticke_status_3cb08e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intelioc',
            name='reference_url',
            field=models.TextField(blank=True),
        ),
    ]
